# Generated by Django 2.0.1 on 2018-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_auto_20180122_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trend',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='trend',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
