# Generated by Django 2.0.1 on 2018-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_auto_20180122_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
