# Generated by Django 2.0.1 on 2018-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_auto_20180122_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='trend',
            name='url',
            field=models.EmailField(max_length=300),
        ),
    ]
