# Generated by Django 2.0.1 on 2018-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_auto_20180124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
