# Generated by Django 2.0.1 on 2018-01-30 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0007_auto_20180130_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 8, 26, 6, 756082, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
